// AUTO-GENERATED by scripts/generate-gallery-manifest.mjs — do not edit by hand.
// Regenerate with: npm run gallery:manifest

import type { GalleryData } from "./galleryData";

export const galleryImages: GalleryData = {
    "avenues": [
        {
            "name": "Acacia Auriculiformis",
            "path": "/gallery/avenues/Acacia Auriculiformis.jpeg"
        },
        {
            "name": "Adansonia Digitata",
            "path": "/gallery/avenues/Adansonia Digitata.jpg"
        },
        {
            "name": "Alstonia Scholaris",
            "path": "/gallery/avenues/Alstonia Scholaris.jpg"
        },
        {
            "name": "Araucaria Columnaris (Christmas Tree)",
            "path": "/gallery/avenues/Araucaria Columnaris (Christmas Tree).jpeg"
        },
        {
            "name": "Azadirachta Indica",
            "path": "/gallery/avenues/Azadirachta Indica.jpeg"
        },
        {
            "name": "Barringtonia Asiatica",
            "path": "/gallery/avenues/Barringtonia Asiatica.jpg"
        },
        {
            "name": "Bauhinia Blakeana",
            "path": "/gallery/avenues/Bauhinia Blakeana.jpg"
        },
        {
            "name": "Bauhinia Purpurea",
            "path": "/gallery/avenues/Bauhinia Purpurea.jpg"
        },
        {
            "name": "Bignonia Megapotamica",
            "path": "/gallery/avenues/Bignonia Megapotamica.jpg"
        },
        {
            "name": "Bolusanthus Speciosus(Wisteria)",
            "path": "/gallery/avenues/Bolusanthus Speciosus(Wisteria).jpg"
        },
        {
            "name": "Bombax Ceiba",
            "path": "/gallery/avenues/Bombax Ceiba.jpeg"
        },
        {
            "name": "Brachychiton Acerifolius",
            "path": "/gallery/avenues/Brachychiton Acerifolius.jpeg"
        },
        {
            "name": "Brachychiton Rupestris",
            "path": "/gallery/avenues/Brachychiton Rupestris.jpg"
        },
        {
            "name": "Brassia Actinophylla",
            "path": "/gallery/avenues/Brassia Actinophylla.jpg"
        },
        {
            "name": "Butea Monosperma",
            "path": "/gallery/avenues/Butea Monosperma.jpeg"
        },
        {
            "name": "Caesalpinia ferrea",
            "path": "/gallery/avenues/Caesalpinia ferrea.jpeg"
        },
        {
            "name": "Callistemon Polandii",
            "path": "/gallery/avenues/Callistemon Polandii.jpg"
        },
        {
            "name": "Calophyllum Inophyllum",
            "path": "/gallery/avenues/Calophyllum Inophyllum.jpg"
        },
        {
            "name": "Cardia Sebestena",
            "path": "/gallery/avenues/Cardia Sebestena.jpg"
        },
        {
            "name": "Cassia Fistula",
            "path": "/gallery/avenues/Cassia Fistula.jpg"
        },
        {
            "name": "Cassia Javanica",
            "path": "/gallery/avenues/Cassia Javanica.jpg"
        },
        {
            "name": "Cassia Siamea",
            "path": "/gallery/avenues/Cassia Siamea.jpeg"
        },
        {
            "name": "Casuarina Equisetifolia",
            "path": "/gallery/avenues/Casuarina Equisetifolia.jpeg"
        },
        {
            "name": "Cerbera Odollam Rubra (Red Pong Pong)",
            "path": "/gallery/avenues/Cerbera Odollam Rubra (Red Pong Pong).jpeg"
        },
        {
            "name": "Chorisia Speciosa Grafted",
            "path": "/gallery/avenues/Chorisia Speciosa Grafted.jpeg"
        },
        {
            "name": "Cochlospermum Regium",
            "path": "/gallery/avenues/Cochlospermum Regium.jpg"
        },
        {
            "name": "Conocarpus Sliver",
            "path": "/gallery/avenues/Conocarpus Sliver.jpeg"
        },
        {
            "name": "Conocarpus",
            "path": "/gallery/avenues/Conocarpus.jpg"
        },
        {
            "name": "Couroupita Guianesis",
            "path": "/gallery/avenues/Couroupita Guianesis.jpg"
        },
        {
            "name": "Delonix Regia",
            "path": "/gallery/avenues/Delonix Regia.jpeg"
        },
        {
            "name": "Dendrolobium Umbellatum",
            "path": "/gallery/avenues/Dendrolobium Umbellatum.jpg"
        },
        {
            "name": "Elaeocarpus Ganitrus (Rudrakash)",
            "path": "/gallery/avenues/Elaeocarpus Ganitrus (Rudrakash).jpeg"
        },
        {
            "name": "Erythrina Indica",
            "path": "/gallery/avenues/Erythrina Indica.jpg"
        },
        {
            "name": "Erythrina Lysistemon",
            "path": "/gallery/avenues/Erythrina Lysistemon.jpg"
        },
        {
            "name": "Ficus Benghalensis",
            "path": "/gallery/avenues/Ficus Benghalensis.jpeg"
        },
        {
            "name": "Ficus Elastica",
            "path": "/gallery/avenues/Ficus Elastica.jpeg"
        },
        {
            "name": "Ficus Lyrata",
            "path": "/gallery/avenues/Ficus Lyrata.jpg"
        },
        {
            "name": "Ficus Religiosa",
            "path": "/gallery/avenues/Ficus Religiosa.jpg"
        },
        {
            "name": "Filicium Decipiens",
            "path": "/gallery/avenues/Filicium Decipiens.jpg"
        },
        {
            "name": "Grevillea Robusta",
            "path": "/gallery/avenues/Grevillea Robusta.jpg"
        },
        {
            "name": "Jacaranda Mimosifolia",
            "path": "/gallery/avenues/Jacaranda Mimosifolia.jpg"
        },
        {
            "name": "Kajelia Pinnata",
            "path": "/gallery/avenues/Kajelia Pinnata.jpeg"
        },
        {
            "name": "Khaya Senegalensis",
            "path": "/gallery/avenues/Khaya Senegalensis.jpg"
        },
        {
            "name": "Lagerstroemia Speciosa",
            "path": "/gallery/avenues/Lagerstroemia Speciosa.jpg"
        },
        {
            "name": "Lawsonia inermis (Henna)",
            "path": "/gallery/avenues/Lawsonia inermis (Henna).jpg"
        },
        {
            "name": "Magnolia Grandiflora",
            "path": "/gallery/avenues/Magnolia Grandiflora.jpg"
        },
        {
            "name": "Melia Dubia (Malabar Neem)",
            "path": "/gallery/avenues/Melia Dubia (Malabar Neem).jpeg"
        },
        {
            "name": "Michelia Champaca",
            "path": "/gallery/avenues/Michelia Champaca.jpg"
        },
        {
            "name": "Millettia Pinnata",
            "path": "/gallery/avenues/Millettia Pinnata.jpg"
        },
        {
            "name": "Millingtonia Hortensis",
            "path": "/gallery/avenues/Millingtonia Hortensis.jpeg"
        },
        {
            "name": "Mimusops Elengi",
            "path": "/gallery/avenues/Mimusops Elengi.jpg"
        },
        {
            "name": "Moringa Drouhardii",
            "path": "/gallery/avenues/Moringa Drouhardii.jpeg"
        },
        {
            "name": "Murraya Koenigii (Curry Leaf)",
            "path": "/gallery/avenues/Murraya Koenigii (Curry Leaf).jpeg"
        },
        {
            "name": "Neolamarckia Cadamba",
            "path": "/gallery/avenues/Neolamarckia Cadamba.jpg"
        },
        {
            "name": "Nyctanthes Arbor-Tristis(Parijat)",
            "path": "/gallery/avenues/Nyctanthes Arbor-Tristis(Parijat).jpeg"
        },
        {
            "name": "Peltophorum Pterocarpum",
            "path": "/gallery/avenues/Peltophorum Pterocarpum.jpg"
        },
        {
            "name": "Podocarpus Gracilior",
            "path": "/gallery/avenues/Podocarpus Gracilior.jpg"
        },
        {
            "name": "Podocarpus Macrophyllus",
            "path": "/gallery/avenues/Podocarpus Macrophyllus.jpg"
        },
        {
            "name": "Polyalthia Pendula",
            "path": "/gallery/avenues/Polyalthia Pendula.jpg"
        },
        {
            "name": "Polyathia Longifolia",
            "path": "/gallery/avenues/Polyathia Longifolia.jpg"
        },
        {
            "name": "Pseudo Bombax Ellipticum",
            "path": "/gallery/avenues/Pseudo Bombax Ellipticum.jpg"
        },
        {
            "name": "Pterocarpus santalinus (Red Sandal)",
            "path": "/gallery/avenues/Pterocarpus santalinus (Red Sandal).jpg"
        },
        {
            "name": "Pterospermum Acerifolium (Kanaka Champa)",
            "path": "/gallery/avenues/Pterospermum Acerifolium (Kanaka Champa).jpg"
        },
        {
            "name": "Putranjiva Roxburghii",
            "path": "/gallery/avenues/Putranjiva Roxburghii.jpg"
        },
        {
            "name": "Samanea Saman (Rain tree)",
            "path": "/gallery/avenues/Samanea Saman (Rain tree).jpeg"
        },
        {
            "name": "Santalum album (White Sandal)",
            "path": "/gallery/avenues/Santalum album (White Sandal).jpg"
        },
        {
            "name": "Saraca Indica",
            "path": "/gallery/avenues/Saraca Indica.jpg"
        },
        {
            "name": "Schizolobum Parahyba(Tower Tree)",
            "path": "/gallery/avenues/Schizolobum Parahyba(Tower Tree).jpg"
        },
        {
            "name": "Spathodea Campanulata",
            "path": "/gallery/avenues/Spathodea Campanulata.jpeg"
        },
        {
            "name": "Sterculia Foetida",
            "path": "/gallery/avenues/Sterculia Foetida.jpg"
        },
        {
            "name": "Swietenia Mahagoni",
            "path": "/gallery/avenues/Swietenia Mahagoni.jpg"
        },
        {
            "name": "Tabebuia Argentea",
            "path": "/gallery/avenues/Tabebuia Argentea.jpg"
        },
        {
            "name": "Tabebuia Avellanedae",
            "path": "/gallery/avenues/Tabebuia Avellanedae.jpg"
        },
        {
            "name": "Tabebuia Donnell-Smithii",
            "path": "/gallery/avenues/Tabebuia Donnell-Smithii.jpg"
        },
        {
            "name": "Tabebuia Rosea",
            "path": "/gallery/avenues/Tabebuia Rosea.jpg"
        },
        {
            "name": "Tecona Grandis",
            "path": "/gallery/avenues/Tecona Grandis.jpeg"
        },
        {
            "name": "Terminalia Arjuna",
            "path": "/gallery/avenues/Terminalia Arjuna.jpg"
        },
        {
            "name": "Terminalia Catappa",
            "path": "/gallery/avenues/Terminalia Catappa.jpg"
        },
        {
            "name": "Terminalia Mantaly Green",
            "path": "/gallery/avenues/Terminalia Mantaly Green.jpg"
        },
        {
            "name": "Terminalia Mantaly Red",
            "path": "/gallery/avenues/Terminalia Mantaly Red.jpg"
        },
        {
            "name": "Terminalia Mantaly Variegated",
            "path": "/gallery/avenues/Terminalia Mantaly Variegated.jpg"
        },
        {
            "name": "Thespesia Populnea (Portia Tree)",
            "path": "/gallery/avenues/Thespesia Populnea (Portia Tree).jpg"
        }
    ],
    "bamboos": [
        {
            "name": "Bamboo Grass",
            "path": "/gallery/bamboos/Bamboo Grass.jpg"
        },
        {
            "name": "Bambusa Multiplex Gold",
            "path": "/gallery/bamboos/Bambusa Multiplex Gold.jpeg"
        },
        {
            "name": "Bambusa Multiplex Green",
            "path": "/gallery/bamboos/Bambusa Multiplex Green.jpg"
        },
        {
            "name": "Bambusa Variegated",
            "path": "/gallery/bamboos/Bambusa Variegated.jpg"
        },
        {
            "name": "Bambusa Ventricosa",
            "path": "/gallery/bamboos/Bambusa Ventricosa.jpg"
        },
        {
            "name": "Bambusa Vulgaris (Golden Bamboo)",
            "path": "/gallery/bamboos/Bambusa Vulgaris (Golden Bamboo).jpg"
        },
        {
            "name": "Blue Pine Bamboo",
            "path": "/gallery/bamboos/Blue Pine Bamboo.jpg"
        },
        {
            "name": "Dendrocalamus Giganteus(Gaint Bamboo)",
            "path": "/gallery/bamboos/Dendrocalamus Giganteus(Gaint Bamboo).jpeg"
        },
        {
            "name": "Equisetum Hyemale(Horse Tail)",
            "path": "/gallery/bamboos/Equisetum Hyemale(Horse Tail).jpeg"
        },
        {
            "name": "Green Bamboo",
            "path": "/gallery/bamboos/Green Bamboo.jpg"
        },
        {
            "name": "Painting Bamboo",
            "path": "/gallery/bamboos/Painting Bamboo.jpg"
        },
        {
            "name": "Phyllostachys Nigra (Black Bamboo)",
            "path": "/gallery/bamboos/Phyllostachys Nigra (Black Bamboo).jpeg"
        },
        {
            "name": "Schizostachyum Brachycladum",
            "path": "/gallery/bamboos/Schizostachyum Brachycladum.jpeg"
        },
        {
            "name": "White Bamboo",
            "path": "/gallery/bamboos/White Bamboo.jpg"
        }
    ],
    "bonsai": [
        {
            "name": "Bonsai 1",
            "path": "/gallery/bonsai/Bonsai 1.jpg"
        },
        {
            "name": "Bonsai 2",
            "path": "/gallery/bonsai/Bonsai 2.jpeg"
        },
        {
            "name": "Bonsai 3",
            "path": "/gallery/bonsai/Bonsai 3.jpg"
        },
        {
            "name": "Bonsai 4",
            "path": "/gallery/bonsai/Bonsai 4.jpeg"
        },
        {
            "name": "Bonsai 5",
            "path": "/gallery/bonsai/Bonsai 5.jpg"
        },
        {
            "name": "Bonsai 6",
            "path": "/gallery/bonsai/Bonsai 6.jpeg"
        },
        {
            "name": "Bonsai 7",
            "path": "/gallery/bonsai/Bonsai 7.jpg"
        },
        {
            "name": "Bonsai 8",
            "path": "/gallery/bonsai/Bonsai 8.jpg"
        },
        {
            "name": "Bonsai 9",
            "path": "/gallery/bonsai/Bonsai 9.jpeg"
        },
        {
            "name": "Bonsai 10",
            "path": "/gallery/bonsai/Bonsai 10.jpg"
        },
        {
            "name": "Bonsai 11",
            "path": "/gallery/bonsai/Bonsai 11.jpg"
        },
        {
            "name": "Bonsai 12",
            "path": "/gallery/bonsai/Bonsai 12.jpg"
        },
        {
            "name": "Bonsai 13",
            "path": "/gallery/bonsai/Bonsai 13.jpg"
        },
        {
            "name": "Bonsai 14",
            "path": "/gallery/bonsai/Bonsai 14.jpg"
        },
        {
            "name": "Bonsai 15",
            "path": "/gallery/bonsai/Bonsai 15.jpg"
        },
        {
            "name": "Bonsai 16",
            "path": "/gallery/bonsai/Bonsai 16.jpeg"
        },
        {
            "name": "Bonsai 17",
            "path": "/gallery/bonsai/Bonsai 17.jpg"
        },
        {
            "name": "Bonsai 18",
            "path": "/gallery/bonsai/Bonsai 18.jpeg"
        },
        {
            "name": "Bonsai 19",
            "path": "/gallery/bonsai/Bonsai 19.jpg"
        },
        {
            "name": "Bonsai 20",
            "path": "/gallery/bonsai/Bonsai 20.jpeg"
        },
        {
            "name": "Bonsai 21",
            "path": "/gallery/bonsai/Bonsai 21.jpeg"
        },
        {
            "name": "Bonsai 22",
            "path": "/gallery/bonsai/Bonsai 22.jpeg"
        },
        {
            "name": "Bonsai 22",
            "path": "/gallery/bonsai/Bonsai 22.jpg"
        },
        {
            "name": "Bonsai 23",
            "path": "/gallery/bonsai/Bonsai 23.jpeg"
        },
        {
            "name": "Bonsai 24",
            "path": "/gallery/bonsai/Bonsai 24.jpeg"
        },
        {
            "name": "Bonsai 25",
            "path": "/gallery/bonsai/Bonsai 25.jpeg"
        }
    ],
    "Malpighia Models": [
        {
            "name": "Malpighia Models_1",
            "path": "/gallery/Malpighia Models/Malpighia Models_1.jpg"
        },
        {
            "name": "Malpighia Models_2",
            "path": "/gallery/Malpighia Models/Malpighia Models_2.jpg"
        },
        {
            "name": "Malpighia Models_3",
            "path": "/gallery/Malpighia Models/Malpighia Models_3.jpg"
        },
        {
            "name": "Malpighia Models_4",
            "path": "/gallery/Malpighia Models/Malpighia Models_4.jpg"
        },
        {
            "name": "Malpighia Models_6",
            "path": "/gallery/Malpighia Models/Malpighia Models_6.jpg"
        },
        {
            "name": "Malpighia Models_9",
            "path": "/gallery/Malpighia Models/Malpighia Models_9.jpg"
        },
        {
            "name": "Malpighia Models_10",
            "path": "/gallery/Malpighia Models/Malpighia Models_10.jpg"
        },
        {
            "name": "Malpighia Models_11",
            "path": "/gallery/Malpighia Models/Malpighia Models_11.jpg"
        },
        {
            "name": "Malpighia Models_12",
            "path": "/gallery/Malpighia Models/Malpighia Models_12.jpg"
        },
        {
            "name": "Malpighia Models_13",
            "path": "/gallery/Malpighia Models/Malpighia Models_13.jpg"
        },
        {
            "name": "Malpighia Models_14",
            "path": "/gallery/Malpighia Models/Malpighia Models_14.jpg"
        },
        {
            "name": "Malpighia Models_15",
            "path": "/gallery/Malpighia Models/Malpighia Models_15.jpg"
        },
        {
            "name": "Malpighia Models_16",
            "path": "/gallery/Malpighia Models/Malpighia Models_16.jpg"
        },
        {
            "name": "Malpighia Models_17",
            "path": "/gallery/Malpighia Models/Malpighia Models_17.jpg"
        },
        {
            "name": "Malpighia Models_18",
            "path": "/gallery/Malpighia Models/Malpighia Models_18.jpg"
        },
        {
            "name": "Malpighia Models_19",
            "path": "/gallery/Malpighia Models/Malpighia Models_19.jpg"
        },
        {
            "name": "Malpighia Models_20",
            "path": "/gallery/Malpighia Models/Malpighia Models_20.jpg"
        },
        {
            "name": "Malpighia Models_21",
            "path": "/gallery/Malpighia Models/Malpighia Models_21.jpg"
        },
        {
            "name": "Malpighia Models_22",
            "path": "/gallery/Malpighia Models/Malpighia Models_22.jpg"
        },
        {
            "name": "Malpighia Models_23",
            "path": "/gallery/Malpighia Models/Malpighia Models_23.jpg"
        },
        {
            "name": "Malpighia Models_24",
            "path": "/gallery/Malpighia Models/Malpighia Models_24.jpg"
        },
        {
            "name": "Malpighia Models_25",
            "path": "/gallery/Malpighia Models/Malpighia Models_25.jpg"
        },
        {
            "name": "Malpighia Models_26",
            "path": "/gallery/Malpighia Models/Malpighia Models_26.jpg"
        },
        {
            "name": "Malpighia Models_27",
            "path": "/gallery/Malpighia Models/Malpighia Models_27.jpg"
        },
        {
            "name": "Malpighia Models_28",
            "path": "/gallery/Malpighia Models/Malpighia Models_28.jpg"
        },
        {
            "name": "Malpighia Models_29",
            "path": "/gallery/Malpighia Models/Malpighia Models_29.jpg"
        },
        {
            "name": "Malpighia Models_30",
            "path": "/gallery/Malpighia Models/Malpighia Models_30.jpg"
        },
        {
            "name": "Malpighia Models_31",
            "path": "/gallery/Malpighia Models/Malpighia Models_31.jpg"
        },
        {
            "name": "Malpighia Models_34",
            "path": "/gallery/Malpighia Models/Malpighia Models_34.jpg"
        },
        {
            "name": "Malpighia Models_35",
            "path": "/gallery/Malpighia Models/Malpighia Models_35.jpg"
        },
        {
            "name": "Malpighia Models_36",
            "path": "/gallery/Malpighia Models/Malpighia Models_36.jpg"
        },
        {
            "name": "Malpighia Models_37",
            "path": "/gallery/Malpighia Models/Malpighia Models_37.jpg"
        },
        {
            "name": "Malpighia Models_38",
            "path": "/gallery/Malpighia Models/Malpighia Models_38.jpg"
        },
        {
            "name": "Malpighia Models_39",
            "path": "/gallery/Malpighia Models/Malpighia Models_39.jpg"
        },
        {
            "name": "Malpighia Models_40",
            "path": "/gallery/Malpighia Models/Malpighia Models_40.jpg"
        },
        {
            "name": "Malpighia Models_41",
            "path": "/gallery/Malpighia Models/Malpighia Models_41.jpg"
        },
        {
            "name": "Malpighia Models_42",
            "path": "/gallery/Malpighia Models/Malpighia Models_42.jpg"
        },
        {
            "name": "Malpighia Models_43",
            "path": "/gallery/Malpighia Models/Malpighia Models_43.jpg"
        },
        {
            "name": "Malpighia Models_44",
            "path": "/gallery/Malpighia Models/Malpighia Models_44.jpg"
        },
        {
            "name": "Malpighia Models_45",
            "path": "/gallery/Malpighia Models/Malpighia Models_45.jpg"
        },
        {
            "name": "Malpighia Models_46",
            "path": "/gallery/Malpighia Models/Malpighia Models_46.jpg"
        },
        {
            "name": "Malpighia Models_47",
            "path": "/gallery/Malpighia Models/Malpighia Models_47.jpg"
        },
        {
            "name": "Malpighia Models_48",
            "path": "/gallery/Malpighia Models/Malpighia Models_48.jpg"
        },
        {
            "name": "Malpighia Models_49",
            "path": "/gallery/Malpighia Models/Malpighia Models_49.jpg"
        },
        {
            "name": "Malpighia Models_50",
            "path": "/gallery/Malpighia Models/Malpighia Models_50.jpg"
        },
        {
            "name": "Malpighia Models_51",
            "path": "/gallery/Malpighia Models/Malpighia Models_51.jpg"
        },
        {
            "name": "Malpighia Models_52",
            "path": "/gallery/Malpighia Models/Malpighia Models_52.jpg"
        },
        {
            "name": "Malpighia Models_54",
            "path": "/gallery/Malpighia Models/Malpighia Models_54.jpg"
        },
        {
            "name": "Malpighia Models_55",
            "path": "/gallery/Malpighia Models/Malpighia Models_55.jpg"
        },
        {
            "name": "Malpighia Models_56",
            "path": "/gallery/Malpighia Models/Malpighia Models_56.jpg"
        },
        {
            "name": "Malpighia Models_57",
            "path": "/gallery/Malpighia Models/Malpighia Models_57.jpg"
        },
        {
            "name": "Malpighia Models_58",
            "path": "/gallery/Malpighia Models/Malpighia Models_58.jpg"
        },
        {
            "name": "Malpighia Models_59",
            "path": "/gallery/Malpighia Models/Malpighia Models_59.jpg"
        },
        {
            "name": "Malpighia Models_60",
            "path": "/gallery/Malpighia Models/Malpighia Models_60.jpg"
        },
        {
            "name": "Malpighia Models_61",
            "path": "/gallery/Malpighia Models/Malpighia Models_61.jpg"
        },
        {
            "name": "Malpighia Models_62",
            "path": "/gallery/Malpighia Models/Malpighia Models_62.jpg"
        },
        {
            "name": "Malpighia Models_64",
            "path": "/gallery/Malpighia Models/Malpighia Models_64.jpg"
        },
        {
            "name": "Malpighia Models_65",
            "path": "/gallery/Malpighia Models/Malpighia Models_65.jpg"
        },
        {
            "name": "Malpighia Models_66",
            "path": "/gallery/Malpighia Models/Malpighia Models_66.jpg"
        },
        {
            "name": "Malpighia Models_67",
            "path": "/gallery/Malpighia Models/Malpighia Models_67.jpg"
        },
        {
            "name": "Malpighia Models_68",
            "path": "/gallery/Malpighia Models/Malpighia Models_68.jpg"
        },
        {
            "name": "Malpighia Models_69",
            "path": "/gallery/Malpighia Models/Malpighia Models_69.jpg"
        },
        {
            "name": "Malpighia Models_70",
            "path": "/gallery/Malpighia Models/Malpighia Models_70.jpg"
        },
        {
            "name": "Malpighia Models_71",
            "path": "/gallery/Malpighia Models/Malpighia Models_71.jpg"
        },
        {
            "name": "Malpighia Models_72",
            "path": "/gallery/Malpighia Models/Malpighia Models_72.jpg"
        },
        {
            "name": "Malpighia Models_73",
            "path": "/gallery/Malpighia Models/Malpighia Models_73.jpg"
        },
        {
            "name": "Malpighia Models_74",
            "path": "/gallery/Malpighia Models/Malpighia Models_74.jpg"
        },
        {
            "name": "Malpighia Models_75",
            "path": "/gallery/Malpighia Models/Malpighia Models_75.jpg"
        },
        {
            "name": "Malpighia Models_76",
            "path": "/gallery/Malpighia Models/Malpighia Models_76.jpg"
        },
        {
            "name": "Malpighia Models_77",
            "path": "/gallery/Malpighia Models/Malpighia Models_77.jpg"
        }
    ],
    "olives": [
        {
            "name": "Olives 1",
            "path": "/gallery/olives/Olives 1.jpeg"
        },
        {
            "name": "Olives 2",
            "path": "/gallery/olives/Olives 2.jpeg"
        },
        {
            "name": "Olives 3",
            "path": "/gallery/olives/Olives 3.jpeg"
        },
        {
            "name": "Olives 4",
            "path": "/gallery/olives/Olives 4.jpeg"
        },
        {
            "name": "Olives 5",
            "path": "/gallery/olives/Olives 5.jpeg"
        },
        {
            "name": "Olives 6",
            "path": "/gallery/olives/Olives 6.jpeg"
        },
        {
            "name": "Olives 7",
            "path": "/gallery/olives/Olives 7.jpeg"
        },
        {
            "name": "Olives 8",
            "path": "/gallery/olives/Olives 8.jpeg"
        },
        {
            "name": "Olives 9",
            "path": "/gallery/olives/Olives 9.jpeg"
        },
        {
            "name": "Olives 10",
            "path": "/gallery/olives/Olives 10.jpeg"
        },
        {
            "name": "Olives 11",
            "path": "/gallery/olives/Olives 11.jpeg"
        },
        {
            "name": "Olives 12",
            "path": "/gallery/olives/Olives 12.jpeg"
        },
        {
            "name": "Olives 13",
            "path": "/gallery/olives/Olives 13.jpeg"
        },
        {
            "name": "Olives 14",
            "path": "/gallery/olives/Olives 14.jpeg"
        },
        {
            "name": "Olives 15",
            "path": "/gallery/olives/Olives 15.jpeg"
        },
        {
            "name": "Olives 16",
            "path": "/gallery/olives/Olives 16.jpeg"
        },
        {
            "name": "Olives 17",
            "path": "/gallery/olives/Olives 17.jpeg"
        },
        {
            "name": "Olives 18",
            "path": "/gallery/olives/Olives 18.jpeg"
        },
        {
            "name": "Olives 19",
            "path": "/gallery/olives/Olives 19.jpeg"
        },
        {
            "name": "Olives 20",
            "path": "/gallery/olives/Olives 20.jpeg"
        },
        {
            "name": "Olives 21",
            "path": "/gallery/olives/Olives 21.jpeg"
        },
        {
            "name": "Olives 22",
            "path": "/gallery/olives/Olives 22.jpeg"
        },
        {
            "name": "Olives 23",
            "path": "/gallery/olives/Olives 23.jpeg"
        },
        {
            "name": "Olives 24",
            "path": "/gallery/olives/Olives 24.jpeg"
        },
        {
            "name": "Olives 25",
            "path": "/gallery/olives/Olives 25.jpeg"
        },
        {
            "name": "Olives 26",
            "path": "/gallery/olives/Olives 26.jpeg"
        }
    ],
    "palms": [
        {
            "name": "Archontophonix Alexandrae",
            "path": "/gallery/palms/Archontophonix Alexandrae.jpg"
        },
        {
            "name": "Areca Catechu Dwarf",
            "path": "/gallery/palms/Areca Catechu Dwarf.jpg"
        },
        {
            "name": "Areca Catechu(Supari Palm)",
            "path": "/gallery/palms/Areca Catechu(Supari Palm).jpg"
        },
        {
            "name": "Beaucarnea recurvata(Nolina)",
            "path": "/gallery/palms/Beaucarnea recurvata(Nolina).jpeg"
        },
        {
            "name": "Bismarckia Nobiis Silver",
            "path": "/gallery/palms/Bismarckia Nobiis Silver.jpg"
        },
        {
            "name": "Butia Capitata",
            "path": "/gallery/palms/Butia Capitata.jpg"
        },
        {
            "name": "Caryota Mitis",
            "path": "/gallery/palms/Caryota Mitis.jpeg"
        },
        {
            "name": "Caryota Urens(fistail palm)",
            "path": "/gallery/palms/Caryota Urens(fistail palm).jpeg"
        },
        {
            "name": "Chamadorea Cataractarum",
            "path": "/gallery/palms/Chamadorea Cataractarum.jpg"
        },
        {
            "name": "Chamaedorea Elegans(Bamboo Palm)",
            "path": "/gallery/palms/Chamaedorea Elegans(Bamboo Palm).jpg"
        },
        {
            "name": "Chamaerops humilis",
            "path": "/gallery/palms/Chamaerops humilis.jpeg"
        },
        {
            "name": "Coconut Ceylon",
            "path": "/gallery/palms/Coconut Ceylon.jpeg"
        },
        {
            "name": "Coconut Green Dwarf",
            "path": "/gallery/palms/Coconut Green Dwarf.jpeg"
        },
        {
            "name": "Cocos Nucifera (Coconut Desi and Hybrid)",
            "path": "/gallery/palms/Cocos Nucifera (Coconut Desi and Hybrid).jpg"
        },
        {
            "name": "Copernicia Alba",
            "path": "/gallery/palms/Copernicia Alba.jpeg"
        },
        {
            "name": "Cycas Circinalis",
            "path": "/gallery/palms/Cycas Circinalis.jpg"
        },
        {
            "name": "Cycas Dioon",
            "path": "/gallery/palms/Cycas Dioon.jpg"
        },
        {
            "name": "Cycas Revoluta",
            "path": "/gallery/palms/Cycas Revoluta.jpg"
        },
        {
            "name": "Dypsis decaryi (Triangular palm)",
            "path": "/gallery/palms/Dypsis decaryi (Triangular palm).jpg"
        },
        {
            "name": "Dypsis Lutescens Dwarf",
            "path": "/gallery/palms/Dypsis Lutescens Dwarf.jpeg"
        },
        {
            "name": "Dypsis lutescens",
            "path": "/gallery/palms/Dypsis lutescens.jpeg"
        },
        {
            "name": "Hyophorbe Legenicaulis",
            "path": "/gallery/palms/Hyophorbe Legenicaulis.jpg"
        },
        {
            "name": "Hyophorbe Verschaffeltii",
            "path": "/gallery/palms/Hyophorbe Verschaffeltii.jpg"
        },
        {
            "name": "Kentia Palm",
            "path": "/gallery/palms/Kentia Palm.jpeg"
        },
        {
            "name": "Latania Lontarodes Yellow (Latania Rubra)",
            "path": "/gallery/palms/Latania Lontarodes Yellow (Latania Rubra).jpg"
        },
        {
            "name": "Latania Lontarodies Red(Latania Rubra)",
            "path": "/gallery/palms/Latania Lontarodies Red(Latania Rubra).jpg"
        },
        {
            "name": "Licuala Grandis",
            "path": "/gallery/palms/Licuala Grandis.jpeg"
        },
        {
            "name": "Licuala Spinosa",
            "path": "/gallery/palms/Licuala Spinosa.jpg"
        },
        {
            "name": "Livistona Chinensis(Table Palm)",
            "path": "/gallery/palms/Livistona Chinensis(Table Palm).jpeg"
        },
        {
            "name": "Musa Palm",
            "path": "/gallery/palms/Musa Palm.jpg"
        },
        {
            "name": "Pritchardia Pacifica",
            "path": "/gallery/palms/Pritchardia Pacifica.jpeg"
        },
        {
            "name": "Ravenala Madagascariensis (Traveller Palm)",
            "path": "/gallery/palms/Ravenala Madagascariensis (Traveller Palm).jpg"
        },
        {
            "name": "Ravenea Rivularis(Ravenea Palm)",
            "path": "/gallery/palms/Ravenea Rivularis(Ravenea Palm).jpg"
        },
        {
            "name": "Red Neck Palm",
            "path": "/gallery/palms/Red Neck Palm.jpeg"
        },
        {
            "name": "Red Wax Sealing Palm",
            "path": "/gallery/palms/Red Wax Sealing Palm.jpg"
        },
        {
            "name": "Rhapis Excelsa",
            "path": "/gallery/palms/Rhapis Excelsa.jpg"
        },
        {
            "name": "Rhapis Palm Mini",
            "path": "/gallery/palms/Rhapis Palm Mini.jpg"
        },
        {
            "name": "Roystonea Regia(Royal Palm)",
            "path": "/gallery/palms/Roystonea Regia(Royal Palm).jpg"
        },
        {
            "name": "Veitchia Merrillii Golden",
            "path": "/gallery/palms/Veitchia Merrillii Golden.jpeg"
        },
        {
            "name": "Veitchia Merrillii Green",
            "path": "/gallery/palms/Veitchia Merrillii Green.jpeg"
        },
        {
            "name": "Washingtonia Filifera",
            "path": "/gallery/palms/Washingtonia Filifera.jpg"
        },
        {
            "name": "Wodyetia Bifurcata (Foxtail Palm)",
            "path": "/gallery/palms/Wodyetia Bifurcata (Foxtail Palm).jpg"
        }
    ],
    "topiaries": [
        {
            "name": "Bougainvillea",
            "path": "/gallery/topiaries/Bougainvillea.jpg"
        },
        {
            "name": "Clusia Rosea",
            "path": "/gallery/topiaries/Clusia Rosea.jpg"
        },
        {
            "name": "Ficus Benjamina",
            "path": "/gallery/topiaries/Ficus Benjamina.jpg"
        },
        {
            "name": "Ficus Black Multiheads",
            "path": "/gallery/topiaries/Ficus Black Multiheads.jpg"
        },
        {
            "name": "Ficus Black",
            "path": "/gallery/topiaries/Ficus Black.jpg"
        },
        {
            "name": "Ficus Mircocarpa",
            "path": "/gallery/topiaries/Ficus Mircocarpa.jpg"
        },
        {
            "name": "Ficus Nuda",
            "path": "/gallery/topiaries/Ficus Nuda.jpg"
        },
        {
            "name": "Ficus Panda Multiheads",
            "path": "/gallery/topiaries/Ficus Panda Multiheads.jpg"
        },
        {
            "name": "Ficus Panda",
            "path": "/gallery/topiaries/Ficus Panda.jpg"
        },
        {
            "name": "Ficus Reginald",
            "path": "/gallery/topiaries/Ficus Reginald.jpg"
        },
        {
            "name": "Ficus Starlight",
            "path": "/gallery/topiaries/Ficus Starlight.jpg"
        },
        {
            "name": "Ficus Triangular",
            "path": "/gallery/topiaries/Ficus Triangular.jpg"
        },
        {
            "name": "Malpighia",
            "path": "/gallery/topiaries/Malpighia.jpg"
        },
        {
            "name": "Multicoloured Bougainvillea",
            "path": "/gallery/topiaries/Multicoloured Bougainvillea.jpg"
        },
        {
            "name": "Syzygium Myrtifolium Dwarf",
            "path": "/gallery/topiaries/Syzygium Myrtifolium Dwarf.jpg"
        },
        {
            "name": "Syzygium Myrtifolium",
            "path": "/gallery/topiaries/Syzygium Myrtifolium.jpg"
        }
    ]
};
